ALTER TABLE public.email_accounts 
ADD COLUMN IF NOT EXISTS imap_host TEXT,
ADD COLUMN IF NOT EXISTS imap_port INTEGER,
ADD COLUMN IF NOT EXISTS imap_user TEXT,
ADD COLUMN IF NOT EXISTS imap_pass TEXT,
ADD COLUMN IF NOT EXISTS imap_encryption TEXT;
